<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>

</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );
?>

<div class="container">
	<div class="col-md-5">
		<div class="row">
			<img class="site-branding" src="https://fakeimg.pl/450?text=logo-elhada" alt="">
		</div>
		<div class="row">
			<div class="col-12">
				<div class="event-table">
					<header>
						<div class="event-table__header">
							Evento Digitales 
						</div>
					</header>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
				</div>
				<div class="event-table">
					<header>
						<div class="event-table__header -live">
							Evento Digitales 
						</div>
						<div class="live-flag">
							<div class="live-icon"></div>
							<div class="live-text">
								en vivo
							</div>
						</div>
					</header>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
					<div class="event">
						<p class="event-info">
							Actividad "Véndele a la mente, no a la gente"<br>
							Fecha: se pospone <br>
							Hora: - <br>
							Plataforma: Telegram <br>
							Cupos: 26 / 40  <br>
						</p>
						<a href="#" class="event-button">
							Registrarme
						</a>
					</div>
				</div>
			</div>
			<div class="col-12">
				<form class="newsletter-form">
					<p class="newsletter-text">¡ey!... ¡entérate de los próximos eventos!</p>
					<p class="newsletter-title">¡Suscríbete a mi boletín</p>
					<input class="newsletter-input" type="text" required>
					<button class="newsletter-button">Suscribirme</button>
					<label>
						<input type="checkbox">
						Acepto los 
						<a href="#">
							términos y condiciones
						</a>
					</label>
				</form>
			</div>
		</div>
	</div>
	<!-- <img src="https://fakeimg.pl/700?text=aqui-va%0ASusana" alt=""> -->
</div>
<footer class="footer">
	<div class="container">		
		<div class="row">
			<div class="footer-left col-12 col-md-3">
				<img class="img" src="https://fakeimg.pl/158x86" alt="">
				<img class="img" src="https://fakeimg.pl/158x86" alt="">
				<div class="footer-donors">
					<img class="donor-img" src="https://fakeimg.pl/60" alt="">
					<img class="donor-img" src="https://fakeimg.pl/60" alt="">
					<img class="donor-img" src="https://fakeimg.pl/60" alt="">
					<img class="donor-img" src="https://fakeimg.pl/60" alt="">
					<img class="donor-img" src="https://fakeimg.pl/60" alt="">
				</div>
			</div>
			<div class="footer-trayectory col-12 col-md-6">
				<h3 class="footer-trayectory__title">
					Trayectoria
				</h3>
				<div class="trayectory-icons">
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">		
					<img class="trayectory-img" src="https://fakeimg.pl/60" alt="">
				</div>
			</div>
			<div class="footer-right col-12 col-md-3">
				<div class="sponsors">
					<h4 class="sponsors-title">Patrocinios</h4>
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
					<img class="sponsor-img" src="https://fakeimg.pl/60" alt="">		
				</div>
				<div class="contact-for-events">
					<h4 class="contact-for-events__title">
						Pautar Eventos
					</h4>
					<p class="contact-for-events__info">
						Contacta con mi mánager: <br>
						Leonardo vera <br>
						+58 412 071 51 23 <br>
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="footer-copyright  col-md-12 col-12">
				<p>Desarrollo y hosting www.redbyte.com.mx 
					<span> | </span>
					Todos los derechos reservados 2019</p>
			</div>
		</div>
	</div>
</footer>






<?php
do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );

